spring.application.name=gestion-pedidos
server.port=8080

# AWS S3
aws.region=us-east-1
aws.s3.bucket=gestion-pedidos-duoc-rafaeln

# Ruta EFS montada en el contenedor
efs.path=/app/efs

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://gestionpedidosrafael.b2clogin.com/a0a8798b-45c4-451d-9c38-09288b770e7b/v2.0/

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://gestionpedidosrafael.b2clogin.com/gestionpedidosrafael.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_susi

spring.security.oauth2.resourceserver.jwt.audiences=9d3b3e50-c1c3-4f59-b28c-68e7bdc7e8d8

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Oracle Cloud
spring.datasource.url=jdbc:oracle:thin:@gestionpedidos_medium?TNS_ADMIN=C:/wallet_gestionPedidos
spring.datasource.username=ADMIN
spring.datasource.password=GestionPedidos2026!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true